Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'anop')
src	= Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('anop', src, depend = ['RT_USING_ANOP'], CPPPATH = CPPPATH)

Return('group')
