Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'pid')
src	= Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('pid', src, depend = ['RT_USING_PID'], CPPPATH = CPPPATH)


Return('group')
